### ISSUE TITLE
Speed of quantization?

### ISSUE THREAD

**Issue by hmms117** [ginnm/DeProt#3]
Hi,

First of all, thanks for the paper and for sharing the code - it seems like a novel and effective approach for discretizing structural elements. The zero shot performance on ProteinGym is impressive!

I am running into speed issues when I run the PDB quantizer. For now, it seems very slow when quantizing large structures. Would it be possible to move parts of the quantization step to GPU/CUDA to speed up?

**Comment by ginnm** [comment]
Yes, Since we are encoding a local-structure rather than individual residue, it will spend more time to encode the local structure. Before pre-training, we collect the pre-training structure token dataset in a HPC cluster with thousands of CPUs and GPUs for about 2 month. It really cost.
